# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./cargo.db:/app/cargo.db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=sqlite:///./cargo.db
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    restart: unless-stopped
